FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g pnpm turbo
COPY . .
RUN turbo prune --scope=web --docker

FROM node:20-alpine AS installer
WORKDIR /app
RUN npm install -g pnpm
COPY --from=base /app/out/json/ .
COPY --from=base /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile
COPY --from=base /app/out/full/ .
RUN pnpm turbo run build --filter=web

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=installer /app/apps/web/next.config.js .
COPY --from=installer /app/apps/web/package.json .
COPY --from=installer /app/apps/web/.next/standalone ./
COPY --from=installer /app/apps/web/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
