FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g pnpm turbo
COPY . .
RUN turbo prune --scope=api --docker

FROM node:20-alpine AS installer
WORKDIR /app
RUN npm install -g pnpm
COPY --from=base /app/out/json/ .
COPY --from=base /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile
COPY --from=base /app/out/full/ .
RUN pnpm turbo run build --filter=api

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=installer /app/apps/api/dist ./dist
COPY --from=installer /app/apps/api/package.json .
EXPOSE 4000
CMD ["node", "dist/index.js"]
