FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g pnpm turbo
COPY . .
RUN turbo prune --scope=worker --docker

FROM node:20-alpine AS installer
WORKDIR /app
RUN npm install -g pnpm
COPY --from=base /app/out/json/ .
COPY --from=base /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile
COPY --from=base /app/out/full/ .
RUN pnpm turbo run build --filter=worker

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=installer /app/apps/worker/dist ./dist
COPY --from=installer /app/apps/worker/package.json .
CMD ["node", "dist/index.js"]
